### A recommendation system seeks to predict the rating or preference a user would give to an item given his old item ratings or preferences. 

### Recommendation systems are used by pretty much every major company in order to enhance the quality of their services.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import os
import warnings

from keras.layers import Input, Embedding, Flatten, Dot, Dense, Concatenate
from keras.models import Model

warnings.filterwarnings('ignore')
%matplotlib inline

## Loading in data

In [2]:
dataset = pd.read_csv('C:\\Users\\HP\\Desktop\\ratings.csv')

In [3]:
dataset.head()

book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [4]:
dataset.shape

(981756, 3)

In [5]:
train, test = train_test_split(dataset, test_size=0.2, random_state=42)

In [6]:
train.head()

book_id  user_id  rating
341848     3423     4608       2
964349     9811    36373       5
645459     6485     2957       4
74960       750    42400       3
358670     3591    36886       5

In [7]:
test.head()

book_id  user_id  rating
646451     6495    19643       5
614851     6175     8563       4
974393     9920    52110       3
21471       215    33864       5
272540     2728    16587       3

In [8]:
n_users = len(dataset.user_id.unique())
n_users

53424

In [9]:
n_books = len(dataset.book_id.unique())
n_books

10000

## Creating Neural Network


In [10]:
# creating book embedding path
book_input = Input(shape=[1], name="Book-Input")
book_embedding = Embedding(n_books+1, 5, name="Book-Embedding")(book_input)
book_vec = Flatten(name="Flatten-Books")(book_embedding)

# creating user embedding path
user_input = Input(shape=[1], name="User-Input")
user_embedding = Embedding(n_users+1, 5, name="User-Embedding")(user_input)
user_vec = Flatten(name="Flatten-Users")(user_embedding)

# concatenate features
conc = Concatenate()([book_vec, user_vec])

# add fully-connected-layers
fc1 = Dense(128, activation='relu')(conc)
fc2 = Dense(32, activation='relu')(fc1)
out = Dense(1)(fc2)

# Create model and compile it
model2 = Model([user_input, book_input], out)
model2.compile('adam', 'mean_squared_error')

In [25]:
from keras.models import load_model

if os.path.exists('regression_model2.h5'):
    model2 = load_model('regression_model2.h5')
else:
    history = model2.fit([train.user_id, train.book_id], train.rating, epochs=5, verbose=1)
    model2.save('regression_model2.h5')
    plt.plot(history.history['loss'])
    plt.xlabel("Epochs")
    plt.ylabel("Training Error")

In [26]:
model2.evaluate([test.user_id, test.book_id], test.rating)

6136/6136 [==============================] - 8s 1ms/step - loss: 0.7132


0.7131532430648804

In [27]:
predictions = model2.predict([test.user_id.head(10), test.book_id.head(10)])

[print(predictions[i], test.rating.iloc[i]) for i in range(0,10)]

[5.136176] 5
[3.748272] 4
[3.3597298] 3
[4.0535803] 5
[3.4103708] 3
[4.0102315] 3
[3.8286157] 3
[4.956117] 4
[4.074676] 3
[4.2032886] 5


[None, None, None, None, None, None, None, None, None, None]

## Making Recommendations

In [28]:
# Creating dataset for making recommendations for the first user
book_data = np.array(list(set(dataset.book_id)))
book_data[:5]

array([1, 2, 3, 4, 5])

In [29]:
user = np.array([1 for i in range(len(book_data))])
user[:5]

array([1, 1, 1, 1, 1])

In [30]:
predictions = model2.predict([user, book_data])

predictions = np.array([a[0] for a in predictions])

recommended_book_ids = (-predictions).argsort()[:5]

recommended_book_ids

array([7946, 5206, 8945, 3627, 3752], dtype=int64)

In [31]:
# print predicted scores
predictions[recommended_book_ids]

array([4.8184423, 4.8123617, 4.8035407, 4.780423 , 4.758326 ],
      dtype=float32)

# ALL BOOKS

In [32]:
books = pd.read_csv('C:\\Users\\HP\\Desktop\\books.csv')
books.head()

id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
1   2        3             3  4640799          491  439554934  9.780440e+12   
2   3    41865         41865  3212258          226  316015849  9.780316e+12   
3   4     2657          2657  3275794          487   61120081  9.780061e+12   
4   5     4671          4671   245494         1356  743273567  9.780743e+12   

                       authors  original_publication_year  \
0              Suzanne Collins                     2008.0   
1  J.K. Rowling, Mary GrandPré                     1997.0   
2              Stephenie Meyer                     2005.0   
3                   Harper Lee                     1960.0   
4          F. Scott Fitzgerald                     1925.0   

                             original_title  ... ratings_count  \
0                          The Hunger Games  ...       4780653   
1  Harry Potter and the Philosopher's Stone  ...       4602479   
2                                  Twilight  ...       3866839   
3                     To Kill a Mockingbird  ...       3198671   
4                          The Great Gatsby  ...       2683664   

  work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0            4942365                   155254      66715     127936   
1            4800065                    75867      75504     101676   
2            3916824                    95009     456191     436802   
3            3340896                    72586      60427     117415   
4            2773745                    51992      86236     197621   

   ratings_3  ratings_4  ratings_5  \
0     560092    1481305    2706317   
1     455024    1156318    3011543   
2     793319     875073    1355439   
3     446835    1001952    1714267   
4     606158     936012     947718   

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...   
1  https://images.gr-assets.com/books/1474154022m...   
2  https://images.gr-assets.com/books/1361039443m...   
3  https://images.gr-assets.com/books/1361975680m...   
4  https://images.gr-assets.com/books/1490528560m...   

                                     small_image_url  
0  https://images.gr-assets.com/books/1447303603s...  
1  https://images.gr-assets.com/books/1474154022s...  
2  https://images.gr-assets.com/books/1361039443s...  
3  https://images.gr-assets.com/books/1361975680s...  
4  https://images.gr-assets.com/books/1490528560s...  

[5 rows x 23 columns]

# RECOMMENDED BOOKS

In [33]:
books[books['id'].isin(recommended_book_ids)]

id  book_id  best_book_id  work_id  books_count        isbn  \
3626  3627  7592279       7592279  9985502           37  1741664489   
3751  3752   140302        477597  1952109          141         NaN   
5205  5206    13066         13066  2257006           31   446695688   
7945  7946    39926         39926   836516           43    60512180   
8944  8945    32529         32529  3214115           40   752848267   

            isbn13          authors  original_publication_year  \
3626  9.781742e+12    John Flanagan                     2011.0   
3751           NaN  Agatha Christie                     1924.0   
5205  9.780447e+12     Carl Hiaasen                     2000.0   
7945  9.780061e+12       Naomi Wolf                     1990.0   
8944  9.780753e+12     Lisa Gardner                     2001.0   

                                         original_title  ... ratings_count  \
3626                                                NaN  ...         29397   
3751                                Poirot Investigates  ...         15476   
5205                                         Sick Puppy  ...         18248   
7945  The Beauty Myth: How Images of Beauty Are Used...  ...         13037   
8944                                  The Next Accident  ...         11261   

     work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
3626              33357                     1089        226        618   
3751              29408                      779        216       1003   
5205              19594                     1069        193        861   
7945              14266                      790        234        790   
8944              13328                      513         49        231   

      ratings_3  ratings_4  ratings_5  \
3626       3569       9564      19380   
3751       6529      10450      11210   
5205       5077       8434       5029   
7945       3493       5552       4197   
8944       2323       5612       5113   

                                              image_url  \
3626  https://images.gr-assets.com/books/1446448563m...   
3751  https://images.gr-assets.com/books/1359475912m...   
5205  https://s.gr-assets.com/assets/nophoto/book/11...   
7945  https://s.gr-assets.com/assets/nophoto/book/11...   
8944  https://images.gr-assets.com/books/1348816896m...   

                                        small_image_url  
3626  https://images.gr-assets.com/books/1446448563s...  
3751  https://images.gr-assets.com/books/1359475912s...  
5205  https://s.gr-assets.com/assets/nophoto/book/50...  
7945  https://s.gr-assets.com/assets/nophoto/book/50...  
8944  https://images.gr-assets.com/books/1348816896s...  

[5 rows x 23 columns]